---
- name: Drop tools virtualenv
  hosts: all
  become: true
  roles:
    - pokerops.monitoring.monitoring
  tasks:
    - name: Remove virtualenv directory
      ansible.builtin.file:
        path: "{{ monitoring_script_venv }}"
        state: absent

    - name: Drop molecule tempdir
      ansible.builtin.file:
        path: "{{ molecule_tmpdir }}"
        state: absent

    - name: Create tempdir file
      ansible.builtin.file:
        path: "{{ molecule_tmpdir }}/test.txt"
        state: touch

- import_playbook: pokerops.monitoring.install
