---
- name: Drop tools virtualenv
  hosts: all
  become: true
  roles:
    - pokerops.monitoring.monitoring
    - nephelaiio.docker
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_facts.os_family == "Debian"

  tasks:
    - name: Remove virtualenv directory
      ansible.builtin.file:
        path: "{{ monitoring_script_venv }}"
        state: absent

    - name: Drop molecule tempdirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ molecule_tmpdir }}"

    - name: Create tempdir directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "uog=rwx"
      loop: "{{ molecule_tmpdir }}"

    - name: Create tempdir files
      ansible.builtin.file:
        path: "{{ item }}/test.txt"
        state: touch
      loop: "{{ molecule_tmpdir }}"

    - name: Run RabbitMQ docker container
      community.docker.docker_container:
        name: rabbitmq
        image: rabbitmq:3-management
        pull: true
        ports:
          - "5672:5672"
          - "15672:15672"
        env:
          RABBITMQ_DEFAULT_VHOST: "{{ rabbitmq_vhost }}"
          RABBITMQ_DEFAULT_USER: "{{ rabbitmq_user_name }}"
          RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_user_pass }}"

    - name: Wait for RabbitMQ
      ansible.builtin.wait_for:
        host: localhost
        port: 5672
        state: started
        timeout: 5
      register: _rabbitmq_status
      retries: 5
      delay: 5
      until: _rabbitmq_status is success

    - name: Ensure RabbitMQ is up
      community.rabbitmq.rabbitmq_vhost:
        login_user: "{{ rabbitmq_user_name }}"
        login_password: "{{ rabbitmq_user_pass }}"
        login_host: localhost
        name: "{{ rabbitmq_vhost }}"
        state: present
      register: _rabbitmq_status
      retries: 5
      delay: 5
      until: _rabbitmq_status is success

    - name: Create RabbitMQ queue
      community.rabbitmq.rabbitmq_queue:
        name: "{{ item }}"
        login_user: "{{ rabbitmq_user_name }}"
        login_password: "{{ rabbitmq_user_pass }}"
        login_host: localhost
        vhost: "{{ rabbitmq_vhost }}"
      loop:
        - "{{ rabbitmq_queue }}"
        - "molecule"

    - name: Create RabbitMQ exchange
      community.rabbitmq.rabbitmq_exchange:
        name: "{{ rabbitmq_queue }}_exchange"
        type: fanout
        login_user: "{{ rabbitmq_user_name }}"
        login_password: "{{ rabbitmq_user_pass }}"
        login_host: localhost
        vhost: "{{ rabbitmq_vhost }}"

    - name: Create RabbitMQ binding
      community.rabbitmq.rabbitmq_binding:
        name: "{{ rabbitmq_queue }}_exchange"
        destination: "{{ item }}"
        destination_type: queue
        login_user: "{{ rabbitmq_user_name }}"
        login_password: "{{ rabbitmq_user_pass }}"
        login_host: localhost
        vhost: "{{ rabbitmq_vhost }}"
      loop:
        - "{{ rabbitmq_queue }}"
        - "molecule"

- name: Import pokeops.monitoring install playbook
  ansible.builtin.import_playbook: pokerops.monitoring.install
