---
- name: Install and configure beat packages
  hosts: all:!localhost
  become: true
  roles:
    - pokerops.monitoring.monitoring
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Verify beats daemons
      ansible.builtin.assert:
        that:
          - service_installed
          - service_running
          - service_enabled
        fail_msg: "{{ fail_uninstalled if not service_installed else (fail_offline if not service_running else fail_disabled) }}"
      vars:
        fail_uninstalled: "{{ item }} service is not installed"
        fail_offline: "{{ item }} service is not running"
        fail_disabled: "{{ item }} service is not enabled"
        service_installed: "{{ item + '.service' in ansible_facts.services }}"
        service_running: "{{ ansible_facts.services[item + '.service'].state == 'running' }}"
        service_enabled: "{{ ansible_facts.services[item + '.service'].status == 'enabled' }}"
      loop:
        - filebeat
        - metricbeat
        - heartbeat-elastic

    - name: Create MongoDB log path
      ansible.builtin.file:
        path: /var/log/mongodb
        state: directory

    - name: Create MongoDB log sample
      ansible.builtin.template:
        src: mongod.j2.log
        dest: /var/log/mongodb/mongod.log
        owner: root
        group: syslog
      vars:
        _date: "{{ ansible_date_time.iso8601 }}"

    - name: Pause for 15 seconds to allow beats to send data
      ansible.builtin.pause:
        seconds: 15

    - name: Slurp filebeat events
      ansible.builtin.slurp:
        src: /var/log/vector/filebeat.log
      register: filebeat_process_log

    - name: Decode filebeat events
      ansible.builtin.set_fact:
        filebeat_events: "{{ _event_lines | map('from_json') }}"
      vars:
        _event_lines: "{{ filebeat_process_log.content | b64decode | split('\n') | reject('equalto', '') }}"

    - name: Verify filebeat mongodb log ingest
      ansible.builtin.assert:
        that:
          - _mongodb | rejectattr('severity', 'defined') | length == 0
          - _mongodb | rejectattr('log_id', 'defined') | length == 0
          - _mongodb | rejectattr('context', 'defined') | length == 0
          - _mongodb | rejectattr('message', 'defined') | length == 0
          - _mongodb | rejectattr('component', 'defined') | length == 0
      vars:
        _mongodb: "{{ filebeat_events | selectattr('log.file.path', 'equalto', _mongodb_path) | list }}"
        _mongodb_path: "/var/log/mongodb/mongod.log"

    - name: Slurp metricbeat events
      ansible.builtin.slurp:
        src: /var/log/vector/metricbeat.log
      register: metricbeat_process_log

    - name: Decode metricbeat events
      ansible.builtin.set_fact:
        metricbeat_events: "{{ _event_lines | map('from_json') }}"
      vars:
        _event_lines: "{{ metricbeat_process_log.content | b64decode | split('\n') | reject('equalto', '') }}"

    - name: Decode process events
      ansible.builtin.set_fact:
        metricbeat_processes_systemd: "{{ metricbeat_processes_all | selectattr('process.executable', 'search', 'systemd$') | list }}"
      vars:
        metricbeat_processes_all: "{{ metricbeat_events | selectattr('metricset.name', 'equalto', 'process') | list }}"

    - name: Verify metricbeat process monitoring
      ansible.builtin.assert:
        that: metricbeat_processes_systemd | length > 0
        success_msg: "{{ metricbeat_processes_systemd | length }} events found for systemd processes"
        fail_msg: "{{ metricbeat_processes_systemd | length }} events found for systemd processes"
