---
name: libvirt
on:
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  libvirt:
    name: libvirt
    runs-on: libvirt
    strategy:
      matrix:
        os:
          - ubuntu2404
          - ubuntu2204
          - ubuntu2004
        scenario:
          - legacy
    env:
      MOLECULE_LOGDIR: "/tmp/logs"
    steps:
      - name: Run devbox tests
        uses: pokerops/ansible-utils@master
        with:
          run: |
            make requirements test \
              MOLECULE_LOGDIR=${{ env.MOLECULE_LOGDIR }} \
              MOLECULE_SCENARIO=${{ matrix.scenario }} \
              MOLECULE_KVM_IMAGE=${{ matrix.os }}

      - name: Upload install logs
        uses: actions/upload-artifact@v4
        with:
          name: install.${{ matrix.os }}
          path: |
            ${{ env.MOLECULE_LOGDIR }}/*.log
          if-no-files-found: ignore
        if: always()
